/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : string,
  'description' : string,
  'courseId' : bigint,
}
export interface AssignmentSubmission {
  'id' : bigint,
  'content' : string,
  'userId' : bigint,
  'submittedAt' : bigint,
  'assignmentId' : bigint,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'facultyId' : bigint,
  'createdAt' : bigint,
  'description' : string,
}
export interface Notification {
  'id' : bigint,
  'userId' : bigint,
  'createdAt' : bigint,
  'type' : string,
  'isRead' : boolean,
  'message' : string,
}
export interface Quiz {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'questions' : Array<QuizQuestion>,
  'courseId' : bigint,
}
export interface QuizQuestion {
  'correctIndex' : bigint,
  'text' : string,
  'options' : Array<string>,
}
export interface QuizResult {
  'id' : bigint,
  'total' : bigint,
  'userId' : bigint,
  'submittedAt' : bigint,
  'score' : bigint,
  'quizId' : bigint,
}
export interface Resource {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'createdAt' : bigint,
  'type' : string,
  'courseId' : bigint,
  'uploadedBy' : bigint,
}
export interface User {
  'id' : bigint,
  'password' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'faculty' : null } |
  { 'student' : null };
export interface _SERVICE {
  'addAssignment' : ActorMethod<[string, bigint, string, string], bigint>,
  'addCourse' : ActorMethod<[string, string, bigint], bigint>,
  'addNotification' : ActorMethod<[bigint, string, string], bigint>,
  'addQuiz' : ActorMethod<[string, bigint, Array<QuizQuestion>], bigint>,
  'addResource' : ActorMethod<[string, string, bigint, string, bigint], bigint>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAssignmentSubmissions' : ActorMethod<[], Array<AssignmentSubmission>>,
  'getAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAssignmentsByCourse' : ActorMethod<[bigint], Array<Assignment>>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getQuizResults' : ActorMethod<[], Array<QuizResult>>,
  'getQuizResultsByUser' : ActorMethod<[bigint], Array<QuizResult>>,
  'getQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getQuizzesByCourse' : ActorMethod<[bigint], Array<Quiz>>,
  'getResources' : ActorMethod<[], Array<Resource>>,
  'getResourcesByCourse' : ActorMethod<[bigint], Array<Resource>>,
  'getStudentCount' : ActorMethod<[], bigint>,
  'getSubmissionsByUser' : ActorMethod<[bigint], Array<AssignmentSubmission>>,
  'getUser' : ActorMethod<[bigint], [] | [User]>,
  'login' : ActorMethod<[string, string], { 'ok' : User } | { 'err' : string }>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'register' : ActorMethod<
    [string, string, UserRole, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'submitAssignment' : ActorMethod<[bigint, bigint, string], bigint>,
  'submitQuizResult' : ActorMethod<[bigint, bigint, bigint, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];