/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizQuestion = IDL.Record({
  'correctIndex' : IDL.Nat,
  'text' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'faculty' : IDL.Null,
  'student' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const AssignmentSubmission = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'userId' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'assignmentId' : IDL.Nat,
});
export const Assignment = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'facultyId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'type' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'userId' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'score' : IDL.Nat,
  'quizId' : IDL.Nat,
});
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'questions' : IDL.Vec(QuizQuestion),
  'courseId' : IDL.Nat,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'type' : IDL.Text,
  'courseId' : IDL.Nat,
  'uploadedBy' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAssignment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addNotification' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addQuiz' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(QuizQuestion)],
      [IDL.Nat],
      [],
    ),
  'addResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAssignmentSubmissions' : IDL.Func(
      [],
      [IDL.Vec(AssignmentSubmission)],
      ['query'],
    ),
  'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAssignmentsByCourse' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'getQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getQuizResultsByUser' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(QuizResult)],
      ['query'],
    ),
  'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getQuizzesByCourse' : IDL.Func([IDL.Nat], [IDL.Vec(Quiz)], ['query']),
  'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getResourcesByCourse' : IDL.Func([IDL.Nat], [IDL.Vec(Resource)], ['query']),
  'getStudentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSubmissionsByUser' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AssignmentSubmission)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      ['query'],
    ),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'submitAssignment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'submitQuizResult' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizQuestion = IDL.Record({
    'correctIndex' : IDL.Nat,
    'text' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({ 'faculty' : IDL.Null, 'student' : IDL.Null });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const AssignmentSubmission = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'userId' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'assignmentId' : IDL.Nat,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'facultyId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'type' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'userId' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'score' : IDL.Nat,
    'quizId' : IDL.Nat,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'questions' : IDL.Vec(QuizQuestion),
    'courseId' : IDL.Nat,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'type' : IDL.Text,
    'courseId' : IDL.Nat,
    'uploadedBy' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAssignment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addNotification' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addQuiz' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(QuizQuestion)],
        [IDL.Nat],
        [],
      ),
    'addResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAssignmentSubmissions' : IDL.Func(
        [],
        [IDL.Vec(AssignmentSubmission)],
        ['query'],
      ),
    'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAssignmentsByCourse' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getQuizResultsByUser' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuizResult)],
        ['query'],
      ),
    'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getQuizzesByCourse' : IDL.Func([IDL.Nat], [IDL.Vec(Quiz)], ['query']),
    'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getResourcesByCourse' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getStudentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSubmissionsByUser' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AssignmentSubmission)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        ['query'],
      ),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'submitAssignment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'submitQuizResult' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };