/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Notification {
    id: bigint;
    userId: bigint;
    createdAt: bigint;
    type: string;
    isRead: boolean;
    message: string;
}
export interface User {
    id: bigint;
    password: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
}
export interface Resource {
    id: bigint;
    url: string;
    title: string;
    createdAt: bigint;
    type: string;
    courseId: bigint;
    uploadedBy: bigint;
}
export interface QuizResult {
    id: bigint;
    total: bigint;
    userId: bigint;
    submittedAt: bigint;
    score: bigint;
    quizId: bigint;
}
export interface Quiz {
    id: bigint;
    title: string;
    createdAt: bigint;
    questions: Array<QuizQuestion>;
    courseId: bigint;
}
export interface QuizQuestion {
    correctIndex: bigint;
    text: string;
    options: Array<string>;
}
export interface AssignmentSubmission {
    id: bigint;
    content: string;
    userId: bigint;
    submittedAt: bigint;
    assignmentId: bigint;
}
export interface Assignment {
    id: bigint;
    title: string;
    createdAt: bigint;
    dueDate: string;
    description: string;
    courseId: bigint;
}
export interface Course {
    id: bigint;
    title: string;
    facultyId: bigint;
    createdAt: bigint;
    description: string;
}
export enum UserRole {
    faculty = "faculty",
    student = "student"
}
export interface backendInterface {
    addAssignment(title: string, courseId: bigint, dueDate: string, description: string): Promise<bigint>;
    addCourse(title: string, description: string, facultyId: bigint): Promise<bigint>;
    addNotification(userId: bigint, message: string, type: string): Promise<bigint>;
    addQuiz(title: string, courseId: bigint, questions: Array<QuizQuestion>): Promise<bigint>;
    addResource(title: string, type: string, courseId: bigint, url: string, uploadedBy: bigint): Promise<bigint>;
    getAllUsers(): Promise<Array<User>>;
    getAssignmentSubmissions(): Promise<Array<AssignmentSubmission>>;
    getAssignments(): Promise<Array<Assignment>>;
    getAssignmentsByCourse(courseId: bigint): Promise<Array<Assignment>>;
    getCourse(id: bigint): Promise<Course | null>;
    getCourses(): Promise<Array<Course>>;
    getNotifications(userId: bigint): Promise<Array<Notification>>;
    getQuizResults(): Promise<Array<QuizResult>>;
    getQuizResultsByUser(userId: bigint): Promise<Array<QuizResult>>;
    getQuizzes(): Promise<Array<Quiz>>;
    getQuizzesByCourse(courseId: bigint): Promise<Array<Quiz>>;
    getResources(): Promise<Array<Resource>>;
    getResourcesByCourse(courseId: bigint): Promise<Array<Resource>>;
    getStudentCount(): Promise<bigint>;
    getSubmissionsByUser(userId: bigint): Promise<Array<AssignmentSubmission>>;
    getUser(id: bigint): Promise<User | null>;
    login(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markNotificationRead(id: bigint): Promise<boolean>;
    register(email: string, password: string, role: UserRole, name: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitAssignment(userId: bigint, assignmentId: bigint, content: string): Promise<bigint>;
    submitQuizResult(userId: bigint, quizId: bigint, score: bigint, total: bigint): Promise<bigint>;
}
import type { Course as _Course, User as _User, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAssignment(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAssignment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAssignment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addCourse(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0, arg1, arg2);
            return result;
        }
    }
    async addNotification(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async addQuiz(arg0: string, arg1: bigint, arg2: Array<QuizQuestion>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuiz(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuiz(arg0, arg1, arg2);
            return result;
        }
    }
    async addResource(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssignmentSubmissions(): Promise<Array<AssignmentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentSubmissions();
            return result;
        }
    }
    async getAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignments();
            return result;
        }
    }
    async getAssignmentsByCourse(arg0: bigint): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsByCourse(arg0);
            return result;
        }
    }
    async getCourse(arg0: bigint): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses();
            return result;
        }
    }
    async getNotifications(arg0: bigint): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return result;
        }
    }
    async getQuizResults(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResults();
            return result;
        }
    }
    async getQuizResultsByUser(arg0: bigint): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResultsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResultsByUser(arg0);
            return result;
        }
    }
    async getQuizzes(): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzes();
            return result;
        }
    }
    async getQuizzesByCourse(arg0: bigint): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzesByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzesByCourse(arg0);
            return result;
        }
    }
    async getResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResources();
            return result;
        }
    }
    async getResourcesByCourse(arg0: bigint): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesByCourse(arg0);
            return result;
        }
    }
    async getStudentCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentCount();
            return result;
        }
    }
    async getSubmissionsByUser(arg0: bigint): Promise<Array<AssignmentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByUser(arg0);
            return result;
        }
    }
    async getUser(arg0: bigint): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: UserRole, arg3: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAssignment(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0, arg1, arg2);
            return result;
        }
    }
    async submitQuizResult(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizResult(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizResult(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_User_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    password: string;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    email: string;
}): {
    id: bigint;
    password: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
} {
    return {
        id: value.id,
        password: value.password,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n4(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    faculty: null;
} | {
    student: null;
}): UserRole {
    return "faculty" in value ? UserRole.faculty : "student" in value ? UserRole.student : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n2(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    faculty: null;
} | {
    student: null;
} {
    return value == UserRole.faculty ? {
        faculty: null
    } : value == UserRole.student ? {
        student: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
